name: Build and Release APK
on:
  push:
    tags:
      - '*'
      - 'v*'
jobs:
  sign-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6
          arguments: assembleRelease
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: extension-app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PWD }}
          keyPassword: ${{ secrets.KEY_PWD }}
      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "extension-app/build/outputs/apk/release/*.apk"
          token: ${{ github.token }}
          generateReleaseNotes: true
